import_history:
  fields:
    days:
      required: false
      default: 7
      example: 30
      selector:
        number:
          min: 1
          max: 365
          unit_of_measurement: days
          mode: box
